/*
# Seed categories from existing data

Migrates all 22 equipment categories from the hardcoded seed data into the categories table.
Each category includes: id, bilingual names, slug, image URL, icon, descriptions, spec_fields (jsonb), display_order.
*/

INSERT INTO categories (id, name_ar, name_en, slug, image, icon, description_ar, description_en, spec_fields, display_order) VALUES
('excavators', 'حفارات', 'Excavators', 'excavators', 'https://cdn.phototourl.com/member/2026-09-26-7f656a4b-4cfe-4319-93dd-9fe4e0818893.png', 'HardHat', 'حفارات بمختلف الأحجام لمشاريع الحفر والتنقيب', 'Excavators of various sizes for digging and excavation projects', '[{"key":"operatingWeight","labelAr":"وزن التشغيل","labelEn":"Operating Weight","unitAr":"طن","unitEn":"ton"},{"key":"enginePower","labelAr":"قدرة المحرك","labelEn":"Engine Power","unitAr":"حصان","unitEn":"HP"},{"key":"bucketCapacity","labelAr":"سعة الدلو","labelEn":"Bucket Capacity","unitAr":"م³","unitEn":"m³"},{"key":"diggingDepth","labelAr":"عمق الحفر","labelEn":"Digging Depth","unitAr":"م","unitEn":"m"}]'::jsonb, 1),
('shovels', 'شيولات', 'Wheel Loaders', 'shovels', 'https://cdn.phototourl.com/member/2026-09-26-5ca84082-ae6d-4a95-856a-165aac541bd4.png', 'Truck', 'شيولات لتحميل ونقل المواد في مواقع المشاريع', 'Wheel loaders for material handling at project sites', '[{"key":"operatingWeight","labelAr":"وزن التشغيل","labelEn":"Operating Weight","unitAr":"طن","unitEn":"ton"},{"key":"bucketCapacity","labelAr":"سعة الدلو","labelEn":"Bucket Capacity","unitAr":"م³","unitEn":"m³"},{"key":"payload","labelAr":"الحمولة","labelEn":"Payload","unitAr":"طن","unitEn":"ton"},{"key":"enginePower","labelAr":"قدرة المحرك","labelEn":"Engine Power","unitAr":"حصان","unitEn":"HP"}]'::jsonb, 2),
('bulldozers', 'البلدوزرات', 'Bulldozers', 'bulldozers', 'https://images.pexels.com/photos/1009926/pexels-photo-1009926.jpeg?auto=compress&cs=tinysrgb&w=800', 'Tractor', 'بلدوزرات لتسوية الأرض ودفع المواد في مواقع البناء', 'Bulldozers for earthmoving and material pushing at construction sites', '[{"key":"operatingWeight","labelAr":"وزن التشغيل","labelEn":"Operating Weight","unitAr":"طن","unitEn":"ton"},{"key":"enginePower","labelAr":"قدرة المحرك","labelEn":"Engine Power","unitAr":"حصان","unitEn":"HP"},{"key":"bladeWidth","labelAr":"عرض الشفرة","labelEn":"Blade Width","unitAr":"م","unitEn":"m"},{"key":"bladeCapacity","labelAr":"سعة الشفرة","labelEn":"Blade Capacity","unitAr":"م³","unitEn":"m³"}]'::jsonb, 3),
('cranes', 'أوناش متحركة', 'Mobile Cranes', 'cranes', 'https://images.pexels.com/photos/209177/pexels-photo-209177.jpeg?auto=compress&cs=tinysrgb&w=800', 'Construction', 'أوناش برافعات متحركة لعمليات الرفع الثقيل في المشاريع', 'Mobile cranes for heavy lifting operations in projects', '[{"key":"liftingCapacity","labelAr":"قدرة الرفع","labelEn":"Lifting Capacity","unitAr":"طن","unitEn":"ton"},{"key":"boomLength","labelAr":"طول الذراع","labelEn":"Boom Length","unitAr":"م","unitEn":"m"},{"key":"liftingHeight","labelAr":"ارتفاع الرفع","labelEn":"Lifting Height","unitAr":"م","unitEn":"m"}]'::jsonb, 4),
('crawler-cranes', 'أوناش زحافة', 'Crawler Cranes', 'crawler-cranes', 'https://images.pexels.com/photos/33488902/pexels-photo-33488902.jpeg?auto=compress&cs=tinysrgb&w=800', 'Construction', 'أوناش زحافة لعمليات الرفع الثقيل في المواقع الصعبة', 'Crawler cranes for heavy lifting in challenging site conditions', '[{"key":"liftingCapacity","labelAr":"قدرة الرفع","labelEn":"Lifting Capacity","unitAr":"طن","unitEn":"ton"},{"key":"boomLength","labelAr":"طول الذراع","labelEn":"Boom Length","unitAr":"م","unitEn":"m"},{"key":"liftingHeight","labelAr":"ارتفاع الرفع","labelEn":"Lifting Height","unitAr":"م","unitEn":"m"},{"key":"operatingWeight","labelAr":"وزن التشغيل","labelEn":"Operating Weight","unitAr":"طن","unitEn":"ton"}]'::jsonb, 5),
('boom-loaders', 'لودرات بوم', 'Backhoe Loaders', 'boom-loaders', 'https://cdn.phototourl.com/member/2026-09-26-d01a1d20-a577-4d6f-b010-f886c1b2a93d.png', 'Tractor', 'لودرات بوم متعددة الاستخدامات لمشاريع التنفيذ', 'Versatile backhoe loaders for construction projects', '[{"key":"operatingWeight","labelAr":"وزن التشغيل","labelEn":"Operating Weight","unitAr":"طن","unitEn":"ton"},{"key":"bucketCapacity","labelAr":"سعة الدلو","labelEn":"Bucket Capacity","unitAr":"م³","unitEn":"m³"},{"key":"payload","labelAr":"الحمولة","labelEn":"Payload","unitAr":"طن","unitEn":"ton"},{"key":"enginePower","labelAr":"قدرة المحرك","labelEn":"Engine Power","unitAr":"حصان","unitEn":"HP"}]'::jsonb, 6),
('bobcat', 'بوبكات', 'Skid Steer Loaders', 'bobcat', 'https://images.pexels.com/photos/16684611/pexels-photo-16684611.jpeg?auto=compress&cs=tinysrgb&w=800', 'Tractor', 'بوبكات صغيرة الحجم للأعمال في المساحات الضيقة', 'Compact skid steer loaders for tight space work', '[{"key":"operatingWeight","labelAr":"وزن التشغيل","labelEn":"Operating Weight","unitAr":"طن","unitEn":"ton"},{"key":"ratedCapacity","labelAr":"السعة المقدرة","labelEn":"Rated Capacity","unitAr":"كجم","unitEn":"kg"},{"key":"enginePower","labelAr":"قدرة المحرك","labelEn":"Engine Power","unitAr":"حصان","unitEn":"HP"},{"key":"bucketCapacity","labelAr":"سعة الدلو","labelEn":"Bucket Capacity","unitAr":"م³","unitEn":"m³"}]'::jsonb, 7),
('telehandlers', 'التيليهاندلر', 'Telehandlers', 'telehandlers', 'https://images.pexels.com/photos/34132984/pexels-photo-34132984.jpeg?auto=compress&cs=tinysrgb&w=800', 'Truck', 'تيليهاندلر لرفع ونقل المواد في ارتفاعات مختلفة', 'Telehandlers for lifting and moving materials at various heights', '[{"key":"liftingCapacity","labelAr":"قدرة الرفع","labelEn":"Lifting Capacity","unitAr":"طن","unitEn":"ton"},{"key":"liftingHeight","labelAr":"ارتفاع الرفع","labelEn":"Lifting Height","unitAr":"م","unitEn":"m"},{"key":"enginePower","labelAr":"قدرة المحرك","labelEn":"Engine Power","unitAr":"حصان","unitEn":"HP"},{"key":"operatingWeight","labelAr":"وزن التشغيل","labelEn":"Operating Weight","unitAr":"طن","unitEn":"ton"}]'::jsonb, 8),
('forklifts', 'رافعات شوكية', 'Forklifts', 'forklifts', 'https://cdn.phototourl.com/member/2026-09-26-fc2b197e-0bbe-4b1f-875e-b7701e941173.png', 'Package', 'رافعات شوكية لرفع ونقل البضائع في المستودعات والمواقع', 'Forklifts for lifting and moving goods in warehouses and sites', '[{"key":"liftingCapacity","labelAr":"قدرة الرفع","labelEn":"Lifting Capacity","unitAr":"طن","unitEn":"ton"},{"key":"liftingHeight","labelAr":"ارتفاع الرفع","labelEn":"Lifting Height","unitAr":"م","unitEn":"m"},{"key":"fuelType","labelAr":"نوع الوقود","labelEn":"Fuel Type","unitAr":"","unitEn":""}]'::jsonb, 9),
('manlift', 'مان لفت', 'Boom Lifts', 'manlift', 'https://cdn.phototourl.com/member/2026-09-26-cda0647c-a4e1-4c20-b75d-bf56f5d809dd.png', 'Wrench', 'منصات عمل مرتفعة للوصول إلى الارتفاعات في المشاريع', 'Aerial work platforms for elevated access in projects', '[{"key":"workingHeight","labelAr":"ارتفاع العمل","labelEn":"Working Height","unitAr":"م","unitEn":"m"},{"key":"platformCapacity","labelAr":"سعة المنصة","labelEn":"Platform Capacity","unitAr":"كجم","unitEn":"kg"},{"key":"horizontalReach","labelAr":"المدى الأفقي","labelEn":"Horizontal Reach","unitAr":"م","unitEn":"m"}]'::jsonb, 10),
('scissor-lift', 'سيزر لفت', 'Scissor Lifts', 'scissor-lift', 'https://images.pexels.com/photos/13532460/pexels-photo-13532460.jpeg?auto=compress&cs=tinysrgb&w=800', 'Layers', 'منصات مقصية للوصول العمودي في الأماكن المغلقة', 'Scissor lifts for vertical access in indoor environments', '[{"key":"workingHeight","labelAr":"ارتفاع العمل","labelEn":"Working Height","unitAr":"م","unitEn":"m"},{"key":"platformCapacity","labelAr":"سعة المنصة","labelEn":"Platform Capacity","unitAr":"كجم","unitEn":"kg"},{"key":"platformSize","labelAr":"حجم المنصة","labelEn":"Platform Size","unitAr":"م","unitEn":"m"}]'::jsonb, 11),
('boom-truck', 'بوم ترك', 'Boom Trucks', 'boom-truck', 'https://cdn.phototourl.com/member/2026-09-26-b095afa2-8c02-428c-b64d-3d433dc05840.png', 'Building2', 'شاحنات برافعات متحركة لعمليات الرفع في المواقع', 'Truck-mounted cranes for lifting operations on site', '[{"key":"liftingCapacity","labelAr":"قدرة الرفع","labelEn":"Lifting Capacity","unitAr":"طن","unitEn":"ton"},{"key":"boomLength","labelAr":"طول الذراع","labelEn":"Boom Length","unitAr":"م","unitEn":"m"},{"key":"truckChassis","labelAr":"هيكل الشاحنة","labelEn":"Truck Chassis","unitAr":"","unitEn":""}]'::jsonb, 12),
('motor-graders', 'الموتر جريدات', 'Motor Graders', 'motor-graders', 'https://images.pexels.com/photos/10643009/pexels-photo-10643009.jpeg?auto=compress&cs=tinysrgb&w=800', 'Truck', 'موتور جريدات لتسوية وتشكيل الطرق والمسارات', 'Motor graders for road leveling and surface grading', '[{"key":"operatingWeight","labelAr":"وزن التشغيل","labelEn":"Operating Weight","unitAr":"طن","unitEn":"ton"},{"key":"enginePower","labelAr":"قدرة المحرك","labelEn":"Engine Power","unitAr":"حصان","unitEn":"HP"},{"key":"bladeWidth","labelAr":"عرض الشفرة","labelEn":"Blade Width","unitAr":"م","unitEn":"m"},{"key":"bladeAngle","labelAr":"زاوية الشفرة","labelEn":"Blade Angle","unitAr":"درجة","unitEn":"°"}]'::jsonb, 13),
('dump-trucks', 'شاحنات قلابة', 'Dump Trucks', 'dump-trucks', 'https://cdn.phototourl.com/member/2026-09-26-e5318f6f-2531-41d7-95a5-97ce8837ed8f.png', 'Truck', 'شاحنات قلابة لنقل المواد والركام في مواقع المشاريع', 'Dump trucks for transporting materials and aggregates at project sites', '[{"key":"payloadCapacity","labelAr":"سعة الحمولة","labelEn":"Payload Capacity","unitAr":"طن","unitEn":"ton"},{"key":"enginePower","labelAr":"قدرة المحرك","labelEn":"Engine Power","unitAr":"حصان","unitEn":"HP"},{"key":"bedCapacity","labelAr":"سعة الصندوق","labelEn":"Bed Capacity","unitAr":"م³","unitEn":"m³"}]'::jsonb, 14),
('rollers', 'الحدارات', 'Rollers & Compactors', 'rollers', 'https://images.pexels.com/photos/29470169/pexels-photo-29470169.jpeg?auto=compress&cs=tinysrgb&w=800', 'Tractor', 'حدارات ودكاكات لضغط التربة والأسفلت في مشاريع الطرق', 'Rollers and compactors for soil and asphalt compaction in road projects', '[{"key":"operatingWeight","labelAr":"وزن التشغيل","labelEn":"Operating Weight","unitAr":"طن","unitEn":"ton"},{"key":"drumWidth","labelAr":"عرض الأسطوانة","labelEn":"Drum Width","unitAr":"م","unitEn":"m"},{"key":"enginePower","labelAr":"قدرة المحرك","labelEn":"Engine Power","unitAr":"حصان","unitEn":"HP"},{"key":"vibrationForce","labelAr":"قوة الاهتزاز","labelEn":"Vibration Force","unitAr":"كيلو نيوتن","unitEn":"kN"}]'::jsonb, 15),
('concrete-pumps', 'مضخات خرسانة', 'Concrete Pumps', 'concrete-pumps', 'https://images.pexels.com/photos/36782541/pexels-photo-36782541.jpeg?auto=compress&cs=tinysrgb&w=800', 'Truck', 'مضخات خرسانة لضخ الخرسانة في مواقع البناء بمستويات مختلفة', 'Concrete pumps for pumping concrete at construction sites at various levels', '[{"key":"maxOutput","labelAr":"أقصى إنتاجية","labelEn":"Max Output","unitAr":"م³/ساعة","unitEn":"m³/h"},{"key":"boomReach","labelAr":"مدى الذراع","labelEn":"Boom Reach","unitAr":"م","unitEn":"m"},{"key":"enginePower","labelAr":"قدرة المحرك","labelEn":"Engine Power","unitAr":"حصان","unitEn":"HP"},{"key":"pumpingPressure","labelAr":"ضغط الضخ","labelEn":"Pumping Pressure","unitAr":"بار","unitEn":"bar"}]'::jsonb, 16),
('concrete-mixers', 'خلطات خرسانة', 'Concrete Mixers', 'concrete-mixers', 'https://images.pexels.com/photos/10068081/pexels-photo-10068081.jpeg?auto=compress&cs=tinysrgb&w=800', 'Truck', 'خلطات خرسانة لنقل وخلط الخرسانة في المواقع', 'Concrete mixers for transporting and mixing concrete at sites', '[{"key":"drumCapacity","labelAr":"سعة الخلاط","labelEn":"Drum Capacity","unitAr":"م³","unitEn":"m³"},{"key":"enginePower","labelAr":"قدرة المحرك","labelEn":"Engine Power","unitAr":"حصان","unitEn":"HP"},{"key":"dischargeHeight","labelAr":"ارتفاع التفريغ","labelEn":"Discharge Height","unitAr":"م","unitEn":"m"}]'::jsonb, 17),
('generators', 'مولدات كهربائية', 'Generators', 'generators', 'https://cdn.phototourl.com/member/2026-09-26-e393b092-436a-4ec9-8043-8ac2e32fca2e.webp', 'Zap', 'مولدات كهربائية لتوفير الطاقة في المواقع النائية', 'Electric generators for power supply at remote sites', '[{"key":"powerOutput","labelAr":"قدرة الإنتاج","labelEn":"Power Output","unitAr":"kVA","unitEn":"kVA"},{"key":"fuelType","labelAr":"نوع الوقود","labelEn":"Fuel Type","unitAr":"","unitEn":""},{"key":"tankCapacity","labelAr":"سعة الخزان","labelEn":"Tank Capacity","unitAr":"لتر","unitEn":"L"},{"key":"enginePower","labelAr":"قدرة المحرك","labelEn":"Engine Power","unitAr":"حصان","unitEn":"HP"}]'::jsonb, 18),
('air-compressors', 'ضواغط هواء', 'Air Compressors', 'air-compressors', 'https://images.pexels.com/photos/31257317/pexels-photo-31257317.jpeg?auto=compress&cs=tinysrgb&w=800', 'Wind', 'ضواغط هواء لتشغيل أدوات الهواء في المواقع', 'Air compressors for powering pneumatic tools at sites', '[{"key":"freeAirDelivery","labelAr":"تدفق الهواء","labelEn":"Free Air Delivery","unitAr":"CFM","unitEn":"CFM"},{"key":"workingPressure","labelAr":"ضغط العمل","labelEn":"Working Pressure","unitAr":"بار","unitEn":"bar"},{"key":"enginePower","labelAr":"قدرة المحرك","labelEn":"Engine Power","unitAr":"حصان","unitEn":"HP"}]'::jsonb, 19),
('water-tankers', 'صهاريج مياه', 'Water Tankers', 'water-tankers', 'https://images.pexels.com/photos/37433004/pexels-photo-37433004.jpeg?auto=compress&cs=tinysrgb&w=800', 'Truck', 'صهاريج مياه لنقل وتوزيع المياه في المواقع', 'Water tankers for transporting and distributing water at sites', '[{"key":"tankCapacity","labelAr":"سعة الخزان","labelEn":"Tank Capacity","unitAr":"لتر","unitEn":"L"},{"key":"enginePower","labelAr":"قدرة المحرك","labelEn":"Engine Power","unitAr":"حصان","unitEn":"HP"},{"key":"pumpFlowRate","labelAr":"معدل ضخ المضخة","labelEn":"Pump Flow Rate","unitAr":"لتر/دقيقة","unitEn":"L/min"}]'::jsonb, 20),
('flatbed-winch', 'سطحات وونش هيدروليك', 'Flatbed & Hydraulic Winch', 'flatbed-winch', 'https://cdn.phototourl.com/member/2026-09-26-41ea18d3-5d23-4aba-a084-0be15bc533e6.png', 'Truck', 'سطحات وونش هيدروليك لنقل المعدات والآليات', 'Flatbed and hydraulic winch trucks for equipment transport', '[{"key":"payloadCapacity","labelAr":"سعة الحمولة","labelEn":"Payload Capacity","unitAr":"طن","unitEn":"ton"},{"key":"winchCapacity","labelAr":"سعة الونش","labelEn":"Winch Capacity","unitAr":"طن","unitEn":"ton"},{"key":"truckType","labelAr":"نوع الشاحنة","labelEn":"Truck Type","unitAr":"","unitEn":""}]'::jsonb, 21),
('lowbed', 'لوابد', 'Lowbed & Heavy Transport', 'lowbed', 'https://cdn.phototourl.com/member/2026-09-26-a03f7f0f-2a03-4090-a2ff-cb5a3deec7ce.png', 'Truck', 'لوابد لنقل المعدات الثقيلة والآليات الكبيرة', 'Lowbed trailers for transporting heavy equipment and large machinery', '[{"key":"payloadCapacity","labelAr":"سعة الحمولة","labelEn":"Payload Capacity","unitAr":"طن","unitEn":"ton"},{"key":"deckLength","labelAr":"طول السطح","labelEn":"Deck Length","unitAr":"م","unitEn":"m"},{"key":"axles","labelAr":"المحاور","labelEn":"Axles","unitAr":"","unitEn":""}]'::jsonb, 22)
ON CONFLICT (id) DO NOTHING;